/**
 * Override: Node — tree-based generic for typed get_node / get_parent.
 * @typeParam Tree - Object type mapping child names to their typed node references.
 *   Contains `[__parent]` symbol key for parent type resolution.
 *   Generated by scene typings with full node tree structure.
 */
declare class Node<Tree extends object = any> extends GodotObject {
  /** Get a child node by path. Known paths (from scene tree) return exact types with autocomplete. */
  get_node<P extends string & _GDGetTreePaths<Tree>>(
    path: P,
  ): _GDGetNode<Tree, P>;
  /** Get a child node by path. Unknown paths return Node. */
  get_node(path: string): Node;
  /** Get a child node or null by path. Known paths return exact type | null. */
  get_node_or_null<P extends string & _GDGetTreePaths<Tree>>(
    path: P,
  ): _GDGetNode<Tree, P> | null;
  /** Get a child node or null by path. Unknown paths return Node | null. */
  get_node_or_null(path: string): Node | null;
  /** Get the parent node. Returns typed parent from scene tree if known. */
  get_parent(): IsAny<Tree> extends true
    ? Node
    : [Tree] extends [{ [__parent]: infer P }]
      ? [P] extends [Node]
        ? P
        : Node
      : Node;
  /** Check if a node exists at path. Known paths (from scene tree) provide autocomplete and return `true`. */
  has_node<P extends string & _GDGetTreePaths<Tree>>(path: P): true;
  /** Check if a node exists at path. Unknown paths return boolean. */
  has_node(path: string): boolean;
  /** Get a child node by index. Known indices (from scene tree) return exact types. */
  get_child<Idx extends number & _GDChildIndices<_GDGetChildren<Tree>>>(
    idx: Idx,
    include_internal?: boolean,
  ): _GDGetChild<Tree, Idx>;
  /** Get a child node by index. Unknown indices return Node. */
  get_child(idx: int, include_internal?: boolean): Node;
  /** Duplicate this node. Returns same type as the original. */
  duplicate(flags?: int): this;
}
