// AUTO-GENERATED from Godot class documentation.
// Manual overrides applied from src/typings/overrides/*.d.ts

/** Contains baked lightmap and dynamic object probe data for {@link LightmapGI}. */
declare class LightmapGIData extends Resource {
  /** The lightmap atlas texture generated by the lightmapper. */
  light_texture: TextureLayered | null;
  /** The lightmap atlas textures generated by the lightmapper. */
  lightmap_textures: Array<TextureLayered>;
  /** The shadowmask atlas textures generated by the lightmapper. */
  shadowmask_textures: Array<TextureLayered>;
  set_light_texture(value: TextureLayered | null): void;
  get_light_texture(): TextureLayered | null;
  set_lightmap_textures(value: Array<TextureLayered>): void;
  get_lightmap_textures(): Array<TextureLayered>;
  set_shadowmask_textures(value: Array<TextureLayered>): void;
  get_shadowmask_textures(): Array<TextureLayered>;

  /** Adds an object that is considered baked within this {@link LightmapGIData}. */
  add_user(path: string, uv_scale: Rect2, slice_index: int, sub_instance: int): void;
  /** Clear all objects that are considered baked within this {@link LightmapGIData}. */
  clear_users(): void;
  /** Returns the number of objects that are considered baked within this {@link LightmapGIData}. */
  get_user_count(): int;
  /** Returns the {@link NodePath} of the baked object at index `user_idx`. */
  get_user_path(user_idx: int): string;
  /**
   * If `true`, lightmaps were baked with directional information. See also {@link LightmapGI.directional}.
   */
  is_using_spherical_harmonics(): boolean;
  /**
   * If `uses_spherical_harmonics` is `true`, tells the engine to treat the lightmap data as if it was baked with directional information.
   * **Note:** Changing this value on already baked lightmaps will not cause them to be baked again. This means the material appearance will look incorrect until lightmaps are baked again, in which case the value set here is discarded as the entire {@link LightmapGIData} resource is replaced by the lightmapper.
   */
  set_uses_spherical_harmonics(uses_spherical_harmonics: boolean): void;

  // enum ShadowmaskMode
  /**
   * Shadowmasking is disabled. No shadowmask texture will be created when baking lightmaps. Existing shadowmask textures will be removed during baking.
   */
  static readonly SHADOWMASK_MODE_NONE: int;
  /**
   * Shadowmasking is enabled. Directional shadows that are outside the {@link DirectionalLight3D.directional_shadow_max_distance} will be rendered using the shadowmask texture. Shadows that are inside the range will be rendered using real-time shadows exclusively. This mode allows for more precise real-time shadows up close, without the potential "smearing" effect that can occur when using lightmaps with a high texel size. The downside is that when the camera moves fast, the transition between the real-time light and shadowmask can be obvious. Also, objects that only have shadows baked in the shadowmask (and no real-time shadows) won't display any shadows up close.
   */
  static readonly SHADOWMASK_MODE_REPLACE: int;
  /**
   * Shadowmasking is enabled. Directional shadows will be rendered with real-time shadows overlaid on top of the shadowmask texture. This mode makes for smoother shadow transitions when the camera moves fast, at the cost of a potential smearing effect for directional shadows that are up close (due to the real-time shadow being mixed with a low-resolution shadowmask). Objects that only have shadows baked in the shadowmask (and no real-time shadows) will keep their shadows up close.
   */
  static readonly SHADOWMASK_MODE_OVERLAY: int;
}
