// AUTO-GENERATED from Godot class documentation.
// Manual overrides applied from src/typings/overrides/*.d.ts

/**
 * Provides virtual methods that can be overridden to create custom {@link PhysicsServer3D} implementations.
 */
declare class PhysicsServer3DExtension extends PhysicsServer3D {
  _area_add_shape(area: RID, shape: RID, transform: Transform3D | Projection, disabled: boolean): void;
  _area_attach_object_instance_id(area: RID, id: int): void;
  _area_clear_shapes(area: RID): void;
  _area_create(): RID;
  _area_get_collision_layer(area: RID): int;
  _area_get_collision_mask(area: RID): int;
  _area_get_object_instance_id(area: RID): int;
  _area_get_param(area: RID, param: int): unknown;
  _area_get_shape(area: RID, shape_idx: int): RID;
  _area_get_shape_count(area: RID): int;
  _area_get_shape_transform(area: RID, shape_idx: int): Transform3D;
  _area_get_space(area: RID): RID;
  _area_get_transform(area: RID): Transform3D;
  _area_remove_shape(area: RID, shape_idx: int): void;
  _area_set_area_monitor_callback(area: RID, callback: Callable): void;
  _area_set_collision_layer(area: RID, layer: int): void;
  _area_set_collision_mask(area: RID, mask: int): void;
  _area_set_monitor_callback(area: RID, callback: Callable): void;
  _area_set_monitorable(area: RID, monitorable: boolean): void;
  _area_set_param(area: RID, param: int, value: unknown): void;
  _area_set_ray_pickable(area: RID, enable: boolean): void;
  _area_set_shape(area: RID, shape_idx: int, shape: RID): void;
  _area_set_shape_disabled(area: RID, shape_idx: int, disabled: boolean): void;
  _area_set_shape_transform(area: RID, shape_idx: int, transform: Transform3D | Projection): void;
  _area_set_space(area: RID, space: RID): void;
  _area_set_transform(area: RID, transform: Transform3D | Projection): void;
  _body_add_collision_exception(body: RID, excepted_body: RID): void;
  _body_add_constant_central_force(body: RID, force: Vector3 | Vector3i): void;
  _body_add_constant_force(body: RID, force: Vector3 | Vector3i, position: Vector3 | Vector3i): void;
  _body_add_constant_torque(body: RID, torque: Vector3 | Vector3i): void;
  _body_add_shape(body: RID, shape: RID, transform: Transform3D | Projection, disabled: boolean): void;
  _body_apply_central_force(body: RID, force: Vector3 | Vector3i): void;
  _body_apply_central_impulse(body: RID, impulse: Vector3 | Vector3i): void;
  _body_apply_force(body: RID, force: Vector3 | Vector3i, position: Vector3 | Vector3i): void;
  _body_apply_impulse(body: RID, impulse: Vector3 | Vector3i, position: Vector3 | Vector3i): void;
  _body_apply_torque(body: RID, torque: Vector3 | Vector3i): void;
  _body_apply_torque_impulse(body: RID, impulse: Vector3 | Vector3i): void;
  _body_attach_object_instance_id(body: RID, id: int): void;
  _body_clear_shapes(body: RID): void;
  _body_create(): RID;
  _body_get_collision_exceptions(body: RID): Array<RID>;
  _body_get_collision_layer(body: RID): int;
  _body_get_collision_mask(body: RID): int;
  _body_get_collision_priority(body: RID): float;
  _body_get_constant_force(body: RID): Vector3;
  _body_get_constant_torque(body: RID): Vector3;
  _body_get_contacts_reported_depth_threshold(body: RID): float;
  _body_get_direct_state(body: RID): PhysicsDirectBodyState3D | null;
  _body_get_max_contacts_reported(body: RID): int;
  _body_get_mode(body: RID): int;
  _body_get_object_instance_id(body: RID): int;
  _body_get_param(body: RID, param: int): unknown;
  _body_get_shape(body: RID, shape_idx: int): RID;
  _body_get_shape_count(body: RID): int;
  _body_get_shape_transform(body: RID, shape_idx: int): Transform3D;
  _body_get_space(body: RID): RID;
  _body_get_state(body: RID, state: int): unknown;
  _body_get_user_flags(body: RID): int;
  _body_is_axis_locked(body: RID, axis: int): boolean;
  _body_is_continuous_collision_detection_enabled(body: RID): boolean;
  _body_is_omitting_force_integration(body: RID): boolean;
  _body_remove_collision_exception(body: RID, excepted_body: RID): void;
  _body_remove_shape(body: RID, shape_idx: int): void;
  _body_reset_mass_properties(body: RID): void;
  _body_set_axis_lock(body: RID, axis: int, lock: boolean): void;
  _body_set_axis_velocity(body: RID, axis_velocity: Vector3 | Vector3i): void;
  _body_set_collision_layer(body: RID, layer: int): void;
  _body_set_collision_mask(body: RID, mask: int): void;
  _body_set_collision_priority(body: RID, priority: float): void;
  _body_set_constant_force(body: RID, force: Vector3 | Vector3i): void;
  _body_set_constant_torque(body: RID, torque: Vector3 | Vector3i): void;
  _body_set_contacts_reported_depth_threshold(body: RID, threshold: float): void;
  _body_set_enable_continuous_collision_detection(body: RID, enable: boolean): void;
  _body_set_force_integration_callback(body: RID, callable: Callable, userdata: unknown): void;
  _body_set_max_contacts_reported(body: RID, amount: int): void;
  _body_set_mode(body: RID, mode: int): void;
  _body_set_omit_force_integration(body: RID, enable: boolean): void;
  _body_set_param(body: RID, param: int, value: unknown): void;
  _body_set_ray_pickable(body: RID, enable: boolean): void;
  _body_set_shape(body: RID, shape_idx: int, shape: RID): void;
  _body_set_shape_disabled(body: RID, shape_idx: int, disabled: boolean): void;
  _body_set_shape_transform(body: RID, shape_idx: int, transform: Transform3D | Projection): void;
  _body_set_space(body: RID, space: RID): void;
  _body_set_state(body: RID, state: int, value: unknown): void;
  _body_set_state_sync_callback(body: RID, callable: Callable): void;
  _body_set_user_flags(body: RID, flags: int): void;
  _body_test_motion(body: RID, from_: Transform3D | Projection, motion: Vector3 | Vector3i, margin: float, max_collisions: int, collide_separation_ray: boolean, recovery_as_collision: boolean, result: unknown): boolean;
  _box_shape_create(): RID;
  _capsule_shape_create(): RID;
  _concave_polygon_shape_create(): RID;
  _cone_twist_joint_get_param(joint: RID, param: int): float;
  _cone_twist_joint_set_param(joint: RID, param: int, value: float): void;
  _convex_polygon_shape_create(): RID;
  _custom_shape_create(): RID;
  _cylinder_shape_create(): RID;
  _end_sync(): void;
  _finish(): void;
  _flush_queries(): void;
  _free_rid(rid: RID): void;
  _generic_6dof_joint_get_flag(joint: RID, axis: int, flag: int): boolean;
  _generic_6dof_joint_get_param(joint: RID, axis: int, param: int): float;
  _generic_6dof_joint_set_flag(joint: RID, axis: int, flag: int, enable: boolean): void;
  _generic_6dof_joint_set_param(joint: RID, axis: int, param: int, value: float): void;
  _get_process_info(process_info: int): int;
  _heightmap_shape_create(): RID;
  _hinge_joint_get_flag(joint: RID, flag: int): boolean;
  _hinge_joint_get_param(joint: RID, param: int): float;
  _hinge_joint_set_flag(joint: RID, flag: int, enabled: boolean): void;
  _hinge_joint_set_param(joint: RID, param: int, value: float): void;
  _init(): void;
  _is_flushing_queries(): boolean;
  _joint_clear(joint: RID): void;
  _joint_create(): RID;
  _joint_disable_collisions_between_bodies(joint: RID, disable: boolean): void;
  _joint_get_solver_priority(joint: RID): int;
  _joint_get_type(joint: RID): int;
  _joint_is_disabled_collisions_between_bodies(joint: RID): boolean;
  _joint_make_cone_twist(joint: RID, body_A: RID, local_ref_A: Transform3D | Projection, body_B: RID, local_ref_B: Transform3D | Projection): void;
  _joint_make_generic_6dof(joint: RID, body_A: RID, local_ref_A: Transform3D | Projection, body_B: RID, local_ref_B: Transform3D | Projection): void;
  _joint_make_hinge(joint: RID, body_A: RID, hinge_A: Transform3D | Projection, body_B: RID, hinge_B: Transform3D | Projection): void;
  _joint_make_hinge_simple(joint: RID, body_A: RID, pivot_A: Vector3 | Vector3i, axis_A: Vector3 | Vector3i, body_B: RID, pivot_B: Vector3 | Vector3i, axis_B: Vector3 | Vector3i): void;
  _joint_make_pin(joint: RID, body_A: RID, local_A: Vector3 | Vector3i, body_B: RID, local_B: Vector3 | Vector3i): void;
  _joint_make_slider(joint: RID, body_A: RID, local_ref_A: Transform3D | Projection, body_B: RID, local_ref_B: Transform3D | Projection): void;
  _joint_set_solver_priority(joint: RID, priority: int): void;
  _pin_joint_get_local_a(joint: RID): Vector3;
  _pin_joint_get_local_b(joint: RID): Vector3;
  _pin_joint_get_param(joint: RID, param: int): float;
  _pin_joint_set_local_a(joint: RID, local_A: Vector3 | Vector3i): void;
  _pin_joint_set_local_b(joint: RID, local_B: Vector3 | Vector3i): void;
  _pin_joint_set_param(joint: RID, param: int, value: float): void;
  _separation_ray_shape_create(): RID;
  _set_active(active: boolean): void;
  _shape_get_custom_solver_bias(shape: RID): float;
  _shape_get_data(shape: RID): unknown;
  _shape_get_margin(shape: RID): float;
  _shape_get_type(shape: RID): int;
  _shape_set_custom_solver_bias(shape: RID, bias: float): void;
  _shape_set_data(shape: RID, data: unknown): void;
  _shape_set_margin(shape: RID, margin: float): void;
  _slider_joint_get_param(joint: RID, param: int): float;
  _slider_joint_set_param(joint: RID, param: int, value: float): void;
  _soft_body_add_collision_exception(body: RID, body_b: RID): void;
  _soft_body_apply_central_force(body: RID, force: Vector3 | Vector3i): void;
  _soft_body_apply_central_impulse(body: RID, impulse: Vector3 | Vector3i): void;
  _soft_body_apply_point_force(body: RID, point_index: int, force: Vector3 | Vector3i): void;
  _soft_body_apply_point_impulse(body: RID, point_index: int, impulse: Vector3 | Vector3i): void;
  _soft_body_create(): RID;
  _soft_body_get_bounds(body: RID): AABB;
  _soft_body_get_collision_exceptions(body: RID): Array<RID>;
  _soft_body_get_collision_layer(body: RID): int;
  _soft_body_get_collision_mask(body: RID): int;
  _soft_body_get_damping_coefficient(body: RID): float;
  _soft_body_get_drag_coefficient(body: RID): float;
  _soft_body_get_linear_stiffness(body: RID): float;
  _soft_body_get_point_global_position(body: RID, point_index: int): Vector3;
  _soft_body_get_pressure_coefficient(body: RID): float;
  _soft_body_get_shrinking_factor(body: RID): float;
  _soft_body_get_simulation_precision(body: RID): int;
  _soft_body_get_space(body: RID): RID;
  _soft_body_get_state(body: RID, state: int): unknown;
  _soft_body_get_total_mass(body: RID): float;
  _soft_body_is_point_pinned(body: RID, point_index: int): boolean;
  _soft_body_move_point(body: RID, point_index: int, global_position: Vector3 | Vector3i): void;
  _soft_body_pin_point(body: RID, point_index: int, pin: boolean): void;
  _soft_body_remove_all_pinned_points(body: RID): void;
  _soft_body_remove_collision_exception(body: RID, body_b: RID): void;
  _soft_body_set_collision_layer(body: RID, layer: int): void;
  _soft_body_set_collision_mask(body: RID, mask: int): void;
  _soft_body_set_damping_coefficient(body: RID, damping_coefficient: float): void;
  _soft_body_set_drag_coefficient(body: RID, drag_coefficient: float): void;
  _soft_body_set_linear_stiffness(body: RID, linear_stiffness: float): void;
  _soft_body_set_mesh(body: RID, mesh: RID): void;
  _soft_body_set_pressure_coefficient(body: RID, pressure_coefficient: float): void;
  _soft_body_set_ray_pickable(body: RID, enable: boolean): void;
  _soft_body_set_shrinking_factor(body: RID, shrinking_factor: float): void;
  _soft_body_set_simulation_precision(body: RID, simulation_precision: int): void;
  _soft_body_set_space(body: RID, space: RID): void;
  _soft_body_set_state(body: RID, state: int, variant: unknown): void;
  _soft_body_set_total_mass(body: RID, total_mass: float): void;
  _soft_body_set_transform(body: RID, transform: Transform3D | Projection): void;
  _soft_body_update_rendering_server(body: RID, rendering_server_handler: PhysicsServer3DRenderingServerHandler): void;
  _space_create(): RID;
  _space_get_contact_count(space: RID): int;
  _space_get_contacts(space: RID): PackedVector3Array;
  _space_get_direct_state(space: RID): PhysicsDirectSpaceState3D | null;
  _space_get_param(space: RID, param: int): float;
  _space_is_active(space: RID): boolean;
  _space_set_active(space: RID, active: boolean): void;
  _space_set_debug_contacts(space: RID, max_contacts: int): void;
  _space_set_param(space: RID, param: int, value: float): void;
  _sphere_shape_create(): RID;
  _step(step: float): void;
  _sync(): void;
  _world_boundary_shape_create(): RID;
  body_test_motion_is_excluding_body(body: RID): boolean;
  body_test_motion_is_excluding_object(object: int): boolean;
}
