// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from TypeScript source files.
// This file makes all named classes available globally.

import { Animal as _Animal } from "./Animal.js";
import { Dog as _Dog } from "./Dog.js";
import { DogOwner as _DogOwner } from "./DogOwner.js";

declare global {
  // From: Animal.ts
  class Animal extends _Animal {}
  // From: Dog.ts
  class Dog extends _Dog {}
  // From: DogOwner.ts
  class DogOwner extends _DogOwner {}
}

export {};
