// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from TypeScript source files.
// This file makes all named classes available globally.

import _Animal from "./Animal.js";
import _Dog from "./Dog.js";
import _DogOwner from "./DogOwner.js";

declare global {
  // From: Animal.ts
  class Animal extends _Animal {}
  // From: Dog.ts
  class Dog extends _Dog {}
  // From: DogOwner.ts
  class DogOwner extends _DogOwner {}
}

export {};
