// AUTO-GENERATED from Godot class documentation.
// Manual overrides applied from typings/_overrides/*.d.ts

/** Custom generator of previews. */
declare class EditorResourcePreviewGenerator extends RefCounted {
  /**
   * If this function returns `true`, the generator will call {@link _generate} or {@link _generate_from_path} for small previews as well.
   * By default, it returns `false`.
   */
  _can_generate_small_preview(): boolean;
  /**
   * Generate a preview from a given resource with the specified size. This must always be implemented.
   * Returning `null` is an OK way to fail and let another generator take care.
   * Care must be taken because this function is always called from a thread (not the main thread).
   * `metadata` dictionary can be modified to store file-specific metadata that can be used in {@link EditorResourceTooltipPlugin._make_tooltip_for_path} (like image size, sample length etc.).
   */
  _generate(resource: Resource, size: Vector2i, metadata: Dictionary): Texture2D | null;
  /**
   * Generate a preview directly from a path with the specified size. Implementing this is optional, as default code will load and call {@link _generate}.
   * Returning `null` is an OK way to fail and let another generator take care.
   * Care must be taken because this function is always called from a thread (not the main thread).
   * `metadata` dictionary can be modified to store file-specific metadata that can be used in {@link EditorResourceTooltipPlugin._make_tooltip_for_path} (like image size, sample length etc.).
   */
  _generate_from_path(path: string, size: Vector2i, metadata: Dictionary): Texture2D | null;
  /**
   * If this function returns `true`, the generator will automatically generate the small previews from the normal preview texture generated by the methods {@link _generate} or {@link _generate_from_path}.
   * By default, it returns `false`.
   */
  _generate_small_preview_automatically(): boolean;
  /** Returns `true` if your generator supports the resource of type `type`. */
  _handles(type_: string): boolean;
  /** Call from within {@link _generate} to request the rendering server draw to the `viewport`. */
  request_draw_and_wait(viewport: RID): void;
}
