// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from TypeScript source files and .tscn scene files.
// Provides global class declarations, get_node overloads, GodotResources, and autoloads.

import type { __CLASS__ as _Anonym } from "./Anonym.ts";
import type { __CLASS__ as _Anonym2 } from "./Anonym2.ts";
import type { Ball as _Ball } from "./Ball.ts";
import type { BaseCharacter as _BaseCharacter } from "./BaseCharacter.ts";
import type { Enemy as _Enemy } from "./Enemy.ts";
import type { __CLASS__ as _GameManager } from "./GameManager.ts";
import type { Level as _Level } from "./Level.ts";
import type { Player as _Player } from "./Player.ts";
import type { __CLASS__ as _nested_Anonym } from "./nested/Anonym.ts";

// Scene nodes for: _Anonym
interface _AnonymSceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _Anonym}>;
  "CollisionShape2D": CollisionShape2D<{[__parent]: _Anonym}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
}

declare module "./Anonym.ts" {
  interface __CLASS__ {
    get_node<P extends string & _GDGetTreePaths<_AnonymSceneNodes>>(path: P): _GDGetNode<_AnonymSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _AnonymSceneNodes>(path: P): _AnonymSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_AnonymSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
    get_parent(): _TilesetObjectsTscn;
  }
}

// Scene nodes for: _Anonym2
interface _Anonym2SceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _Anonym2}>;
  "CollisionShape2D": CollisionShape2D<{[__parent]: _Anonym2}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
}

declare module "./Anonym2.ts" {
  interface __CLASS__ {
    get_node<P extends string & _GDGetTreePaths<_Anonym2SceneNodes>>(path: P): _GDGetNode<_Anonym2SceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _Anonym2SceneNodes>(path: P): _Anonym2SceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_Anonym2SceneNodes>>(path: P): true;
    has_node(path: string): boolean;
  }
}

// Scene nodes for: _Ball
interface _BallSceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _Ball}>;
  "Timer": Timer<{[__parent]: _Ball}> | null;
  "Label": Label<{[__parent]: _Ball}> | null;
}

declare module "./Ball.ts" {
  interface Ball {
    get_node<P extends string & _GDGetTreePaths<_BallSceneNodes>>(path: P): _GDGetNode<_BallSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _BallSceneNodes>(path: P): _BallSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_BallSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
    get_parent(): _TilesetObjectsTscn;
  }
}

// Scene nodes for: _Enemy
interface _EnemySceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _Enemy}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
  "HitBox": Area2D<{[__parent]: _Enemy}>;
  "HitBox/CollisionShape2D": CollisionShape2D<{[__parent]: Area2D}>;
}

declare module "./Enemy.ts" {
  interface Enemy {
    get_node<P extends string & _GDGetTreePaths<_EnemySceneNodes>>(path: P): _GDGetNode<_EnemySceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _EnemySceneNodes>(path: P): _EnemySceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_EnemySceneNodes>>(path: P): true;
    has_node(path: string): boolean;
    get_parent(): _Level;
  }
}

// Scene nodes for: _Level
interface _LevelSceneNodes {
  "Player": Player & {[__script_tree]: _PlayerSceneNodes};
  "Enemy": Enemy & {[__script_tree]: _EnemySceneNodes};
  "TilesetObjects": _TilesetObjectsTscn;
  "Background": Sprite2D<{[__parent]: _Level}>;
  "UI": CanvasLayer<{[__parent]: _Level}>;
  "UI/ScoreLabel": Label<{[__parent]: CanvasLayer}>;
  "TilesetObjectsMap": _TilesetObjectsTscn;
  "Level2": _Level2Tscn;
  "ExtraNode": Label<{[__parent]: _Level}> | null;
  "TilesetObjects2": _TilesetObjectsTscn | null;
  "ExtraSprite": Sprite2D<{[__parent]: _Level}> | null;
}

declare module "./Level.ts" {
  interface Level {
    get_node<P extends string & _GDGetTreePaths<_LevelSceneNodes>>(path: P): _GDGetNode<_LevelSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _LevelSceneNodes>(path: P): _LevelSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_LevelSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
  }
}

// Scene nodes for: _nested_Anonym
interface _nested_AnonymSceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _nested_Anonym}>;
  "CollisionShape2D": CollisionShape2D<{[__parent]: _nested_Anonym}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
}

declare module "./nested/Anonym.ts" {
  interface __CLASS__ {
    get_node<P extends string & _GDGetTreePaths<_nested_AnonymSceneNodes>>(path: P): _GDGetNode<_nested_AnonymSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _nested_AnonymSceneNodes>(path: P): _nested_AnonymSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_nested_AnonymSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
  }
}

// Scene nodes for: _Player
interface _PlayerSceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _Player}>;
  "CollisionShape2D": CollisionShape2D<{[__parent]: _Player}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
  "HealthBar": ProgressBar<{[__parent]: _Player}>;
  "%HealthBar": ProgressBar<{[__parent]: _Player}>;
}

declare module "./Player.ts" {
  interface Player {
    get_node<P extends string & _GDGetTreePaths<_PlayerSceneNodes>>(path: P): _GDGetNode<_PlayerSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _PlayerSceneNodes>(path: P): _PlayerSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_PlayerSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
    get_parent(): _Level;
  }
}

// Scene nodes for: _BaseCharacter
interface _BaseCharacterSceneNodes {
  "Sprite2D": Sprite2D<{[__parent]: _BaseCharacter}>;
  "Sprite2D/AnimationPlayer": AnimationPlayer<{[__parent]: Sprite2D}>;
  "HitBox": Area2D<{[__parent]: _BaseCharacter}> | null;
  "HitBox/CollisionShape2D": CollisionShape2D<{[__parent]: Area2D}> | null;
  "CollisionShape2D": CollisionShape2D<{[__parent]: _BaseCharacter}> | null;
  "HealthBar": ProgressBar<{[__parent]: _BaseCharacter}> | null;
  "%HealthBar": ProgressBar<{[__parent]: _BaseCharacter}> | null;
}

declare module "./BaseCharacter.ts" {
  interface BaseCharacter {
    get_node<P extends string & _GDGetTreePaths<_BaseCharacterSceneNodes>>(path: P): _GDGetNode<_BaseCharacterSceneNodes, P>;
    get_node(path: string): Node;
    get_node_or_null<P extends keyof _BaseCharacterSceneNodes>(path: P): _BaseCharacterSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
    has_node<P extends string & _GDGetTreePaths<_BaseCharacterSceneNodes>>(path: P): true;
    has_node(path: string): boolean;
  }
}

// Scene nodes for scriptless scene: _Level2Tscn
type _Level2Tscn = Node<{
  [__parent]: _Level;
  "ExtraSprite": Sprite2D<{[__parent]: _Level2Tscn}>;
}>

// Scene nodes for scriptless scene: _TilesetObjectsTscn
type _TilesetObjectsTscn = TileMap<{
  [__parent]: _Level;
}>

declare global {
  // From: Ball.ts
  class Ball extends _Ball {}
  // From: BaseCharacter.ts
  class BaseCharacter extends _BaseCharacter {}
  // From: Enemy.ts
  class Enemy extends _Enemy {}
  // From: Level.ts
  class Level extends _Level {}
  // From: Player.ts
  class Player extends _Player {}
  interface GodotResources {
    "res://ALevel.tscn": PackedScene<_Level>;
    "res://Anonym.tscn": PackedScene<_Anonym>;
    "res://Anonym2.tscn": PackedScene<_Anonym2>;
    "res://BallA.tscn": PackedScene<_Ball>;
    "res://BallB.tscn": PackedScene<_Ball>;
    "res://Enemy.tscn": PackedScene<_Enemy>;
    "res://Level.tscn": PackedScene<_Level>;
    "res://Level1.tscn": PackedScene<_Level>;
    "res://Level2.tscn": PackedScene<_Level2Tscn>;
    "res://nested/Anonym.tscn": PackedScene<_nested_Anonym>;
    "res://Player.tscn": PackedScene<_Player>;
    "res://TilesetObjects.tscn": PackedScene<_TilesetObjectsTscn>;
    "res://Anonym.gd": typeof _Anonym;
    "res://Anonym2.gd": typeof _Anonym2;
    "res://Ball.gd": typeof _Ball;
    "res://BaseCharacter.gd": typeof _BaseCharacter;
    "res://Enemy.gd": typeof _Enemy;
    "res://GameManager.gd": typeof _GameManager;
    "res://Level.gd": typeof _Level;
    "res://Player.gd": typeof _Player;
    "res://nested/Anonym.gd": typeof _nested_Anonym;
    "res://player_material.tres": ShaderMaterial;
  }
  // Autoload singletons from project.godot
  const GameManager: _GameManager;
}

export {};
