// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from TypeScript source files.
// This file makes all named classes available globally.

import { Player as _Player } from "./Player.js";

declare global {
  // From: Player.ts
  class Player extends _Player {}
}

export {};
