// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from .tscn scene files.
// Provides get_node/get_node_or_null overloads and GodotResources entries.

import type { __CLASS__ as _Anonym } from "./Anonym.ts";
import type { __CLASS__ as _Anonym2 } from "./Anonym2.ts";
import type { Ball as _Ball } from "./Ball.ts";
import type { Player as _Player } from "./Player.ts";
import type { __CLASS__ as _nested_Anonym } from "./nested/Anonym.ts";

// Scene nodes for: Player
interface PlayerSceneNodes {
  "Sprite2D": Sprite2D;
  "CollisionShape2D": CollisionShape2D;
  "Sprite2D/AnimationPlayer": AnimationPlayer;
}

declare module "./Player.ts" {
  interface Player {
    get_node<P extends keyof PlayerSceneNodes>(path: P): PlayerSceneNodes[P];
    get_node(path: string): Node;
    get_node_or_null<P extends keyof PlayerSceneNodes>(path: P): PlayerSceneNodes[P] | null;
    get_node_or_null(path: string): Node | null;
  }
}

// Resource path → type mappings for load()/preload()
declare global {
  interface GodotResources {
    "res://Player.tscn": PackedScene<_Player>;
    "res://Anonym.gd": _Anonym;
    "res://Anonym2.gd": _Anonym2;
    "res://Ball.gd": _Ball;
    "res://Player.gd": _Player;
    "res://nested/Anonym.gd": _nested_Anonym;
  }
}

export {};
