// AUTO-GENERATED — do not edit manually.
// Generated by ts2gd from .tscn scene files.
// Provides get_node/get_node_or_null overloads for scene node paths.

// Scene nodes for: Player
declare module "./Player.ts" {
  interface Player {
    get_node(path: "Sprite2D"): Sprite2D;
    get_node_or_null(path: "Sprite2D"): Sprite2D;
    get_node(path: "Collision"): CollisionShape2D;
    get_node_or_null(path: "Collision"): CollisionShape2D;
    get_node(path: string): Node;
    get_node_or_null(path: string): Node | null;
  }
}

export {};
