export { convertTsToGd, type ConvertOptions } from './converter/ts-to-gd/index.js';
export { convertGdToTs, type GdToTsOptions } from './converter/gd-to-ts/index.js';
export { GDScriptParser } from './parser/gdscript/index.js';
export { createTsProgram } from './parser/typescript/index.js';
export { SourceMapper } from './sourcemap/index.js';
export { generateClassTypings } from './typings/classes.js';
export { generateSceneTypings } from './typings/scenes.js';
export { generateGodotDocsTypings } from './typings/godot-docs.js';
export { GodotClassRegistry, generateGodotRegistry, parseGodotVersion } from './typings/godot-registry.js';
export { FileCache } from './cache/index.js';
export { Watcher, type WatcherOptions } from './watcher/index.js';
export { resolveRegistry, resolveConfig, loadConfig, type TsToGdConfig, type ResolvedConfig, type ResolveRegistryOptions } from './config/index.js';
export type { TransformResult, TransformDiagnostic, TransformContext } from './converter/common/index.js';
export { default as eslintPlugin } from './eslint/plugin.js';
