import ts from 'typescript';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, relative, basename } from 'path';
import { createTsProgram } from '../parser/typescript/index.js';

export interface ClassTypingsOptions {
  /** Root directory containing TS source files */
  rootDir: string;
  /** TS files to scan for class declarations */
  files: string[];
  /** Output path for the generated .d.ts file */
  outputPath: string;
  /** Path to tsconfig.json (optional) */
  tsConfigPath?: string;
}

/**
 * Scans TS files for root-level named class declarations and generates
 * a global declaration file so classes are available globally (like in GDScript).
 */
export function generateClassTypings(options: ClassTypingsOptions): void {
  const program = createTsProgram({
    rootDir: options.rootDir,
    files: options.files,
    tsConfigPath: options.tsConfigPath,
  });

  const checker = program.getTypeChecker();
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED — do not edit manually.');
  lines.push('// Generated by ts2gd from TypeScript source files.');
  lines.push('// This file makes all named classes available globally.');
  lines.push('');

  for (const filePath of options.files) {
    const sourceFile = program.getSourceFile(filePath);
    if (!sourceFile) continue;

    for (const statement of sourceFile.statements) {
      if (!ts.isClassDeclaration(statement) || !statement.name) continue;

      const className = statement.name.text;
      const relativePath = relative(options.rootDir, filePath).replace(/\\/g, '/');

      lines.push(`// From: ${relativePath}`);
      lines.push(`declare class ${className} {`);

      for (const member of statement.members) {
        if (ts.isPropertyDeclaration(member) && member.name) {
          const name = member.name.getText(sourceFile);
          const isStatic = member.modifiers?.some(m => m.kind === ts.SyntaxKind.StaticKeyword);
          const staticPrefix = isStatic ? 'static ' : '';
          const typeStr = member.type
            ? member.type.getText(sourceFile)
            : 'any';
          lines.push(`  ${staticPrefix}${name}: ${typeStr};`);
        }

        if (ts.isMethodDeclaration(member) && member.name) {
          const name = member.name.getText(sourceFile);
          const isStatic = member.modifiers?.some(m => m.kind === ts.SyntaxKind.StaticKeyword);
          const staticPrefix = isStatic ? 'static ' : '';
          const params = member.parameters
            .map(p => {
              const pName = p.name.getText(sourceFile);
              const pType = p.type ? p.type.getText(sourceFile) : 'any';
              const optional = p.questionToken || p.initializer ? '?' : '';
              return `${pName}${optional}: ${pType}`;
            })
            .join(', ');
          const returnType = member.type
            ? member.type.getText(sourceFile)
            : 'void';
          lines.push(`  ${staticPrefix}${name}(${params}): ${returnType};`);
        }

        if (ts.isConstructorDeclaration(member)) {
          const params = member.parameters
            .map(p => {
              const pName = p.name.getText(sourceFile);
              const pType = p.type ? p.type.getText(sourceFile) : 'any';
              const optional = p.questionToken || p.initializer ? '?' : '';
              return `${pName}${optional}: ${pType}`;
            })
            .join(', ');
          lines.push(`  constructor(${params});`);
        }
      }

      lines.push('}');
      lines.push('');
    }
  }

  writeFileSync(options.outputPath, lines.join('\n'));
}
