import ts from 'typescript';
import { writeFileSync } from 'fs';
import { relative, dirname } from 'path';
import { createTsProgram } from '../parser/typescript/index.ts';

export interface ClassTypingsOptions {
  /** Root directory containing TS source files */
  rootDir: string;
  /** TS files to scan for class declarations */
  files: string[];
  /** Output path for the generated .d.ts file */
  outputPath: string;
  /** Path to tsconfig.json (optional) */
  tsConfigPath?: string;
}

/**
 * Scans TS files for root-level named class declarations and generates
 * a global declaration file so classes are available globally (like in GDScript).
 * Uses import + declare global to reference source classes without duplicating members.
 */
export function generateClassTypings(options: ClassTypingsOptions): void {
  const program = createTsProgram({
    rootDir: options.rootDir,
    files: options.files,
    tsConfigPath: options.tsConfigPath,
  });

  const imports: string[] = [];
  const declarations: string[] = [];

  const outputDir = dirname(options.outputPath);

  for (const filePath of options.files) {
    const sourceFile = program.getSourceFile(filePath);
    if (!sourceFile) continue;

    for (const statement of sourceFile.statements) {
      if (!ts.isClassDeclaration(statement) || !statement.name) continue;

      const className = statement.name.text;
      const commentPath = relative(options.rootDir, filePath).replace(/\\/g, '/');
      let importPath = relative(outputDir, filePath).replace(/\\/g, '/').replace(/\.ts$/, '.js');
      if (!importPath.startsWith('.')) {
        importPath = './' + importPath;
      }

      const alias = `_${className}`;
      imports.push(`import ${alias} from "${importPath}";`);
      declarations.push(`  // From: ${commentPath}`);
      declarations.push(`  class ${className} extends ${alias} {}`);
    }
  }

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED — do not edit manually.');
  lines.push('// Generated by ts2gd from TypeScript source files.');
  lines.push('// This file makes all named classes available globally.');
  lines.push('');

  if (imports.length > 0) {
    lines.push(...imports);
    lines.push('');
    lines.push('declare global {');
    lines.push(...declarations);
    lines.push('}');
    lines.push('');
    lines.push('export {};');
  }

  lines.push('');
  writeFileSync(options.outputPath, lines.join('\n'));
}
