import { readFileSync, readdirSync, statSync } from 'fs';
import { join, relative, extname } from 'path';

interface SceneNode {
  name: string;
  type: string;
  parent: string;
  script?: string;
  children: SceneNode[];
}

interface SceneInfo {
  filePath: string;
  rootType: string;
  scriptPath?: string;
  nodes: SceneNode[];
}

/**
 * Parses a .tscn file and extracts node hierarchy and script references.
 */
function parseScene(filePath: string): SceneInfo | null {
  const content = readFileSync(filePath, 'utf-8');
  const nodes: SceneNode[] = [];
  let rootType = '';
  let scriptPath: string | undefined;

  // Parse [node ...] sections
  const nodeRegex = /\[node\s+([^\]]+)\]/g;
  let match: RegExpExecArray | null;

  while ((match = nodeRegex.exec(content)) !== null) {
    const attrs = match[1]!;
    const name = extractAttr(attrs, 'name');
    const type = extractAttr(attrs, 'type');
    const parent = extractAttr(attrs, 'parent');

    if (name && type) {
      nodes.push({ name, type, parent: parent || '.', children: [] });
    }
  }

  // Parse root node type from [node name="Root" type="Node2D"]
  // The root node has no parent attribute
  const rootNode = nodes.find((n) => n.parent === '.');
  if (rootNode) {
    rootType = rootNode.type;
  }

  // Parse script reference
  const scriptRegex =
    /\[ext_resource\s+[^\]]*path="([^"]+\.gd)"[^\]]*type="Script"/;
  const scriptMatch = scriptRegex.exec(content);
  if (scriptMatch) {
    scriptPath = scriptMatch[1];
  }

  if (!rootType && nodes.length === 0) return null;

  return {
    filePath,
    rootType,
    scriptPath,
    nodes,
  };
}

function extractAttr(attrs: string, name: string): string | undefined {
  const regex = new RegExp(`${name}="([^"]+)"`);
  const match = regex.exec(attrs);
  return match?.[1];
}

/**
 * Builds the full node path for each node in the scene tree.
 */
function buildNodePaths(nodes: SceneNode[]): Map<string, string> {
  const paths = new Map<string, string>();

  // Build parent-child relationships
  const rootNodes = nodes.filter((n) => n.parent === '.');
  for (const root of rootNodes) {
    paths.set(root.name, root.name);
  }

  // Non-root nodes
  for (const node of nodes) {
    if (node.parent === '.') continue;
    const parentPath = node.parent === '.' ? '' : node.parent;
    const fullPath = parentPath ? `${parentPath}/${node.name}` : node.name;
    paths.set(fullPath, node.type);
  }

  return paths;
}

export interface SceneTypingsOptions {
  /** Directory containing .tscn files */
  scenesDir: string;
  /** Output path for the generated .d.ts file */
  outputPath: string;
  /** Map from script path to class name */
  scriptClassMap?: Map<string, string>;
}

/**
 * Generates TypeScript declaration augmentations for getNode() autocomplete.
 * Scans .tscn files for node hierarchies and creates typed getNode overloads.
 */
export function generateSceneTypings(options: SceneTypingsOptions): string {
  const scenes = findSceneFiles(options.scenesDir);
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED — do not edit manually.');
  lines.push('// Generated by ts2gd from Godot scene files.');
  lines.push('// Provides getNode() autocomplete for scene node paths.');
  lines.push('');

  for (const scenePath of scenes) {
    const scene = parseScene(scenePath);
    if (!scene) continue;

    const relPath = relative(options.scenesDir, scenePath).replace(/\\/g, '/');
    const className = scene.scriptPath
      ? (options.scriptClassMap?.get(scene.scriptPath) ?? scene.rootType)
      : scene.rootType;

    if (scene.nodes.length === 0) continue;

    lines.push(`// Scene: ${relPath}`);
    lines.push(`declare module "${relPath}" {`);
    lines.push(`  interface ${className} {`);

    // Generate getNode overloads for each node path
    for (const node of scene.nodes) {
      if (node.parent === '.') continue; // skip root

      const path =
        node.parent === '.' ? node.name : `${node.parent}/${node.name}`;

      lines.push(`    getNode(path: "${path}"): ${node.type};`);
    }

    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function findSceneFiles(dir: string): string[] {
  const results: string[] = [];

  try {
    const entries = readdirSync(dir);
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      try {
        const stat = statSync(fullPath);
        if (stat.isDirectory()) {
          // Skip addons and hidden dirs
          if (!entry.startsWith('.') && entry !== 'addons') {
            results.push(...findSceneFiles(fullPath));
          }
        } else if (extname(entry) === '.tscn') {
          results.push(fullPath);
        }
      } catch {
        // Skip inaccessible files
      }
    }
  } catch {
    // Skip inaccessible dirs
  }

  return results;
}
